
FROM node:18-bullseye

WORKDIR /app


COPY package*.json ./
COPY tsconfig.json ./

RUN npm install


COPY src/ ./src/

ENV NODE_OPTIONS="--max-old-space-size=4096"

RUN npm run build

ENV NODE_OPTIONS="--max-old-space-size=1024"

CMD ["npm", "run", "worker"]


